package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestInspectReportsAntiSlopRules(t *testing.T) {
	t.Parallel()

	directory := t.TempDir()
	filename := filepath.Join(directory, "slop.go")
	source := `package slop

type UnknownAlias = any
type UnknownType any
type UnsafeDictionary map[string]any
type RequestShape struct{}
type Payload struct{ ID string }

func unknownParameter(value any) { _ = value }
func anonymousParameter(value *struct{ ID string }) { _ = value }
func unsafeDictionaryParameter(values map[string]any) { _ = values }
func knownValueWidening() { var value any = Payload{ID: "known"}; _ = value }
func chainedTypeAssertions(value interface{ Value() any }) { _ = value.Value().(any).(Payload) }
func allowedCause(cause any) { _ = cause }
func safeDictionary(values map[string]Payload) { _ = values }
`
	if err := os.WriteFile(filename, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}

	findings, err := inspect([]string{directory})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := len(findings), 9; got != want {
		t.Fatalf("got %d findings, want %d: %#v", got, want, findings)
	}

	wantRules := []string{
		"no-chained-type-assertions",
		"no-known-value-widening",
		"no-object-parameters",
		"no-shape-in-symbol-names",
		"no-unknown-parameters",
		"no-unknown-type-aliases",
		"no-unsafe-dictionary-type",
	}
	for _, rule := range wantRules {
		if !hasRule(findings, rule) {
			t.Errorf("missing %s in %#v", rule, findings)
		}
	}
}

func TestInspectSkipsTestsAndGeneratedFiles(t *testing.T) {
	t.Parallel()

	directory := t.TempDir()
	files := map[string]string{
		"ignored_test.go": "package slop\nfunc ignored(value any) {}\n",
		"generated.go":    "// Code generated by test. DO NOT EDIT.\npackage slop\nfunc ignored(value any) {}\n",
		"clean.go":        "package slop\nfunc clean(value string) {}\n",
	}
	for name, source := range files {
		if err := os.WriteFile(filepath.Join(directory, name), []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	findings, err := inspect([]string{directory})
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Fatalf("unexpected findings: %#v", findings)
	}
}

func hasRule(findings []finding, rule string) bool {
	for _, finding := range findings {
		if finding.rule == rule {
			return true
		}
	}
	return false
}
