/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students/$id'
import { Route as AuthenticatedSetupOnboardRouteImport } from './routes/_authenticated/setup/onboard'
import { Route as AuthenticatedSettingsWhatsappRouteImport } from './routes/_authenticated/settings/whatsapp'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsEmbedRouteImport } from './routes/_authenticated/settings/embed'
import { Route as AuthenticatedSettingsBudgetRouteImport } from './routes/_authenticated/settings/budget'
import { Route as AuthenticatedParentsIdRouteImport } from './routes/_authenticated/parents/$id'
import { Route as AuthenticatedDashboardRetrievalLabRouteImport } from './routes/_authenticated/dashboard/retrieval-lab'
import { Route as AuthenticatedDashboardMetricsRouteImport } from './routes/_authenticated/dashboard/metrics'
import { Route as AuthenticatedDashboardClassesRouteImport } from './routes/_authenticated/dashboard/classes'
import { Route as AuthenticatedDashboardAiUsageRouteImport } from './routes/_authenticated/dashboard/ai-usage'

const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupOnboardRoute =
  AuthenticatedSetupOnboardRouteImport.update({
    id: '/setup/onboard',
    path: '/setup/onboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsWhatsappRoute =
  AuthenticatedSettingsWhatsappRouteImport.update({
    id: '/settings/whatsapp',
    path: '/settings/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsEmbedRoute =
  AuthenticatedSettingsEmbedRouteImport.update({
    id: '/settings/embed',
    path: '/settings/embed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBudgetRoute =
  AuthenticatedSettingsBudgetRouteImport.update({
    id: '/settings/budget',
    path: '/settings/budget',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentsIdRoute = AuthenticatedParentsIdRouteImport.update({
  id: '/parents/$id',
  path: '/parents/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRetrievalLabRoute =
  AuthenticatedDashboardRetrievalLabRouteImport.update({
    id: '/retrieval-lab',
    path: '/retrieval-lab',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMetricsRoute =
  AuthenticatedDashboardMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClassesRoute =
  AuthenticatedDashboardClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiUsageRoute =
  AuthenticatedDashboardAiUsageRouteImport.update({
    id: '/ai-usage',
    path: '/ai-usage',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/export': typeof AuthenticatedExportRoute
  '/join/$slug': typeof JoinSlugRoute
  '/dashboard/ai-usage': typeof AuthenticatedDashboardAiUsageRoute
  '/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/dashboard/retrieval-lab': typeof AuthenticatedDashboardRetrievalLabRoute
  '/parents/$id': typeof AuthenticatedParentsIdRoute
  '/settings/budget': typeof AuthenticatedSettingsBudgetRoute
  '/settings/embed': typeof AuthenticatedSettingsEmbedRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/setup/onboard': typeof AuthenticatedSetupOnboardRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/export': typeof AuthenticatedExportRoute
  '/join/$slug': typeof JoinSlugRoute
  '/dashboard/ai-usage': typeof AuthenticatedDashboardAiUsageRoute
  '/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/dashboard/retrieval-lab': typeof AuthenticatedDashboardRetrievalLabRoute
  '/parents/$id': typeof AuthenticatedParentsIdRoute
  '/settings/budget': typeof AuthenticatedSettingsBudgetRoute
  '/settings/embed': typeof AuthenticatedSettingsEmbedRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/setup/onboard': typeof AuthenticatedSetupOnboardRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/activate': typeof ActivateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/join/$slug': typeof JoinSlugRoute
  '/_authenticated/dashboard/ai-usage': typeof AuthenticatedDashboardAiUsageRoute
  '/_authenticated/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/_authenticated/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/_authenticated/dashboard/retrieval-lab': typeof AuthenticatedDashboardRetrievalLabRoute
  '/_authenticated/parents/$id': typeof AuthenticatedParentsIdRoute
  '/_authenticated/settings/budget': typeof AuthenticatedSettingsBudgetRoute
  '/_authenticated/settings/embed': typeof AuthenticatedSettingsEmbedRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/_authenticated/setup/onboard': typeof AuthenticatedSetupOnboardRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/dashboard'
    | '/export'
    | '/join/$slug'
    | '/dashboard/ai-usage'
    | '/dashboard/classes'
    | '/dashboard/metrics'
    | '/dashboard/retrieval-lab'
    | '/parents/$id'
    | '/settings/budget'
    | '/settings/embed'
    | '/settings/users'
    | '/settings/whatsapp'
    | '/setup/onboard'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/dashboard'
    | '/export'
    | '/join/$slug'
    | '/dashboard/ai-usage'
    | '/dashboard/classes'
    | '/dashboard/metrics'
    | '/dashboard/retrieval-lab'
    | '/parents/$id'
    | '/settings/budget'
    | '/settings/embed'
    | '/settings/users'
    | '/settings/whatsapp'
    | '/setup/onboard'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/join/$slug'
    | '/_authenticated/dashboard/ai-usage'
    | '/_authenticated/dashboard/classes'
    | '/_authenticated/dashboard/metrics'
    | '/_authenticated/dashboard/retrieval-lab'
    | '/_authenticated/parents/$id'
    | '/_authenticated/settings/budget'
    | '/_authenticated/settings/embed'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/whatsapp'
    | '/_authenticated/setup/onboard'
    | '/_authenticated/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  JoinSlugRoute: typeof JoinSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup/onboard': {
      id: '/_authenticated/setup/onboard'
      path: '/setup/onboard'
      fullPath: '/setup/onboard'
      preLoaderRoute: typeof AuthenticatedSetupOnboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/embed': {
      id: '/_authenticated/settings/embed'
      path: '/settings/embed'
      fullPath: '/settings/embed'
      preLoaderRoute: typeof AuthenticatedSettingsEmbedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/budget': {
      id: '/_authenticated/settings/budget'
      path: '/settings/budget'
      fullPath: '/settings/budget'
      preLoaderRoute: typeof AuthenticatedSettingsBudgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parents/$id': {
      id: '/_authenticated/parents/$id'
      path: '/parents/$id'
      fullPath: '/parents/$id'
      preLoaderRoute: typeof AuthenticatedParentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/retrieval-lab': {
      id: '/_authenticated/dashboard/retrieval-lab'
      path: '/retrieval-lab'
      fullPath: '/dashboard/retrieval-lab'
      preLoaderRoute: typeof AuthenticatedDashboardRetrievalLabRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/metrics': {
      id: '/_authenticated/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AuthenticatedDashboardMetricsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/classes': {
      id: '/_authenticated/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof AuthenticatedDashboardClassesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-usage': {
      id: '/_authenticated/dashboard/ai-usage'
      path: '/ai-usage'
      fullPath: '/dashboard/ai-usage'
      preLoaderRoute: typeof AuthenticatedDashboardAiUsageRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAiUsageRoute: typeof AuthenticatedDashboardAiUsageRoute
  AuthenticatedDashboardClassesRoute: typeof AuthenticatedDashboardClassesRoute
  AuthenticatedDashboardMetricsRoute: typeof AuthenticatedDashboardMetricsRoute
  AuthenticatedDashboardRetrievalLabRoute: typeof AuthenticatedDashboardRetrievalLabRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAiUsageRoute: AuthenticatedDashboardAiUsageRoute,
    AuthenticatedDashboardClassesRoute: AuthenticatedDashboardClassesRoute,
    AuthenticatedDashboardMetricsRoute: AuthenticatedDashboardMetricsRoute,
    AuthenticatedDashboardRetrievalLabRoute:
      AuthenticatedDashboardRetrievalLabRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedParentsIdRoute: typeof AuthenticatedParentsIdRoute
  AuthenticatedSettingsBudgetRoute: typeof AuthenticatedSettingsBudgetRoute
  AuthenticatedSettingsEmbedRoute: typeof AuthenticatedSettingsEmbedRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsWhatsappRoute: typeof AuthenticatedSettingsWhatsappRoute
  AuthenticatedSetupOnboardRoute: typeof AuthenticatedSetupOnboardRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedParentsIdRoute: AuthenticatedParentsIdRoute,
  AuthenticatedSettingsBudgetRoute: AuthenticatedSettingsBudgetRoute,
  AuthenticatedSettingsEmbedRoute: AuthenticatedSettingsEmbedRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsWhatsappRoute: AuthenticatedSettingsWhatsappRoute,
  AuthenticatedSetupOnboardRoute: AuthenticatedSetupOnboardRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActivateRoute: ActivateRoute,
  JoinSlugRoute: JoinSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
